// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconFileStatusU({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 0.9411764705882353;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 16 17" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path d="M10.75 0c.199 0 .39.08.53.22l3.5 3.5c.14.14.22.331.22.53v3.085h-1.5V5h-1.25A2.25 2.25 0 0 1 10 2.75V1.5H3.75c-.69 0-1.25.56-1.25 1.25v10.5c0 .69.56 1.25 1.25 1.25h4.03a4.3 4.3 0 0 0 .557 1.5H3.75A2.75 2.75 0 0 1 1 13.25V2.75A2.75 2.75 0 0 1 3.75 0z" /><path d="M12.499 14.784c.703 0 1.191-.434 1.191-1.274V9.335h1.602v4.36c0 1.47-1.08 2.427-2.793 2.427-1.709 0-2.788-.957-2.788-2.427v-4.36h1.601v4.175c0 .85.484 1.274 1.187 1.274" /></svg>;
}