// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconThemes({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 0.9411764705882353;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 16 17" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path d="M15.977 15.01a1 1 0 0 1-1 1H6.184l9.433-3.907q.194-.081.36-.195z" opacity={0.15} /><path d="M15.758 9.895a1 1 0 0 1-.54 1.306l-8.13 3.367 7.226-7.225q.147-.148.257-.315z" opacity={0.3} /><path d="M13.598 5.238a1 1 0 0 1 0 1.415l-6.213 6.211 3.902-9.42q.08-.195.118-.397z" opacity={0.45} /><path d="M9.82 1.765a1 1 0 0 1 .541 1.306L7 11.186V1Q6.999.781 6.953.576z" opacity={0.6} /><path d="M5 0a1 1 0 0 1 1 1v12a3 3 0 1 1-6 0V1a1 1 0 0 1 1-1zM3 12a1 1 0 1 0 0 2 1 1 0 0 0 0-2" /></svg>;
}