// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconSymbolInlinedDuo({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 1;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 16 16" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path fillRule="evenodd" d="M8 16c-6.588 0-8-1.412-8-8s1.412-8 8-8 8 1.412 8 8-1.412 8-8 8" clipRule="evenodd" opacity={0.2} /><path d="M7.75 11.75a.75.75 0 0 1 0-1.5h1.44L5.887 6.948a1.5 1.5 0 1 1 1.06-1.06l3.302 3.301V7.75a.75.75 0 0 1 1.5 0V11a.75.75 0 0 1-.75.75z" /></svg>;
}