// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconReplaceAll({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 1;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 16 16" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path stroke="#000" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M1.75 12.25h10a2.5 2.5 0 0 0 2.5-2.5v-.625m-9.5 6.125-3-3 3-3M14.25 3.75h-10a2.5 2.5 0 0 0-2.5 2.5v.625M11.25.75l3 3-3 3" /><path fillRule="evenodd" d="M10.72.22a.75.75 0 0 1 1.06 0l3 3a.75.75 0 0 1 0 1.06l-3 3a.75.75 0 1 1-1.06-1.06l1.72-1.72H4.25A1.75 1.75 0 0 0 2.5 6.25v.625a.75.75 0 0 1-1.5 0V6.25A3.25 3.25 0 0 1 4.25 3h8.19l-1.72-1.72a.75.75 0 0 1 0-1.06m-5.44 8.5a.75.75 0 0 1 0 1.06L3.56 11.5h8.19a1.75 1.75 0 0 0 1.75-1.75v-.625a.75.75 0 0 1 1.5 0v.625A3.25 3.25 0 0 1 11.75 13H3.56l1.72 1.72a.75.75 0 1 1-1.06 1.06l-3-3a.75.75 0 0 1 0-1.06l3-3a.75.75 0 0 1 1.06 0" clipRule="evenodd" /><path d="M4.22 8.72a.75.75 0 1 1 1.06 1.06L3.56 11.5h8.19a1.75 1.75 0 0 0 1.75-1.75v-.625a.75.75 0 0 1 1.5 0v.625A3.25 3.25 0 0 1 11.75 13H3.56l1.72 1.72a.75.75 0 1 1-1.06 1.06l-3-3a.75.75 0 0 1 0-1.06zM11.78 7.28a.75.75 0 1 1-1.06-1.06l1.72-1.72H4.25A1.75 1.75 0 0 0 2.5 6.25v.625a.75.75 0 0 1-1.5 0V6.25A3.25 3.25 0 0 1 4.25 3h8.19l-1.72-1.72A.75.75 0 1 1 11.78.22l3 3a.75.75 0 0 1 0 1.06z" /></svg>;
}