// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconFileStatusDot({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 1;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 16 16" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path d="M10.75 0c.199 0 .39.08.53.22l3.5 3.5c.14.14.22.331.22.53v4.166a5 5 0 0 0-1.5-.392V5h-1.25A2.25 2.25 0 0 1 10 2.75V1.5H3.75c-.69 0-1.25.56-1.25 1.25v10.5c0 .69.56 1.25 1.25 1.25h4.479c.171.547.435 1.052.771 1.5H3.75A2.75 2.75 0 0 1 1 13.25V2.75A2.75 2.75 0 0 1 3.75 0z" /><path d="M16 13a3 3 0 1 1-6 0 3 3 0 0 1 6 0" /></svg>;
}