// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconCommitArrow({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 1.1875;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 19 16" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path fillRule="evenodd" d="M9 2a6 6 0 0 1 5.951 5.252L15 7.25h1.818l-1.434-2.073-.041-.066a.75.75 0 0 1 1.226-.848l.047.06 2.25 3.25.001.002q.011.018.02.035.024.039.044.078l.021.058.022.068q.009.033.015.067l.002.014Q19 7.947 19 8a1 1 0 0 1-.01.118q-.007.034-.016.067l-.022.068q-.01.03-.021.058a1 1 0 0 1-.043.078l-.02.035-.002.003-2.25 3.25a.75.75 0 1 1-1.232-.854l1.434-2.073H15l-.049-.003a5.999 5.999 0 0 1-11.903 0L3 8.75H1.75a.75.75 0 0 1 0-1.5H3l.048.002A6 6 0 0 1 9 2m0 1.5a4.5 4.5 0 1 0 0 9 4.5 4.5 0 0 0 0-9" clipRule="evenodd" /></svg>;
}