// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconSymbolIgnoredFill({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 1;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 16 16" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path fillRule="evenodd" d="M8 0c6.588 0 8 1.412 8 8s-1.412 8-8 8-8-1.412-8-8 1.412-8 8-8m3.53 4.47a.75.75 0 0 0-1.06 0l-6 6a.75.75 0 1 0 1.06 1.06l6-6a.75.75 0 0 0 0-1.06" clipRule="evenodd" /></svg>;
}