// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconConvo({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 1.125;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 18 16" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path d="M14.977 6.406a5 5 0 0 1 2.05 7.559l.753.755a.75.75 0 0 1-.53 1.28H13a4.98 4.98 0 0 1-3.477-1.41 8 8 0 0 0 1.52-.689A3.5 3.5 0 0 0 13 14.5h2.444a.75.75 0 0 1 .03-1.025 3.496 3.496 0 0 0-.55-5.397 8 8 0 0 0 .053-1.672" /><path fillRule="evenodd" d="M7 0c1.032 0 2.013.224 2.897.626a7.02 7.02 0 0 1 3.834 4.443A7 7 0 0 1 7 14H.75a.75.75 0 0 1-.531-1.28l1.33-1.33A7 7 0 0 1 7 0m0 1.5a5.5 5.5 0 0 0-3.888 9.389.75.75 0 0 1 0 1.061l-.55.55H7a5.5 5.5 0 1 0 0-11" clipRule="evenodd" /></svg>;
}