// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconBrandVsCode({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 1;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 16 16" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path d="M4.7 9.913 1.95 11.998a.67.67 0 0 1-.851-.037l-.882-.802a.667.667 0 0 1 0-.986L2.6 8zM11.01.333a.586.586 0 0 1 1 .414v3.62L7.222 8 4.7 6.086z" opacity={0.75} /><path d="m11.548 15.945.037.005zM1.1 4.04A.67.67 0 0 1 1.95 4l10.059 7.631v3.62a.586.586 0 0 1-1 .415L.218 5.827a.667.667 0 0 1 0-.986z" opacity={0.65} /><path d="M12.147 15.86a1 1 0 0 1-1.137-.193.586.586 0 0 0 1-.415V.747a.586.586 0 0 0-1-.414c.3-.3.755-.377 1.137-.193l3.296 1.585a1 1 0 0 1 .567.901v10.748a1 1 0 0 1-.567.901z" /></svg>;
}