// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconCodeBlockFill({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 1;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 16 16" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path fillRule="evenodd" d="M8 0c1.516 0 2.784.078 3.825.307 1.05.23 1.916.624 2.58 1.288s1.058 1.53 1.288 2.58C15.922 5.215 16 6.484 16 8s-.078 2.784-.307 3.825c-.23 1.05-.623 1.916-1.288 2.58-.664.665-1.53 1.058-2.58 1.288C10.785 15.922 9.516 16 8 16s-2.784-.078-3.825-.307c-1.05-.23-1.916-.623-2.58-1.288-.664-.664-1.058-1.53-1.288-2.58C.078 10.785 0 9.516 0 8s.078-2.784.307-3.825c.23-1.05.624-1.916 1.288-2.58S3.125.537 4.175.307C5.215.078 6.484 0 8 0m-.752 5.19a.75.75 0 0 0-1.059.062l-2 2.25a.75.75 0 0 0 0 .996l2 2.25a.75.75 0 1 0 1.122-.996L5.754 8 7.31 6.248a.75.75 0 0 0-.063-1.059m2.563.062a.75.75 0 0 0-1.122.996L10.246 8 8.69 9.752a.75.75 0 1 0 1.122.996l2-2.25a.75.75 0 0 0 0-.996z" clipRule="evenodd" /></svg>;
}