// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconSymbolDiffstatDuo({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 1;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 16 16" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path d="M8 0C1.412 0 0 1.412 0 8s1.412 8 8 8 8-1.412 8-8-1.412-8-8-8" opacity={0.2} /><path d="M8.75 4.296a.75.75 0 0 0-1.5 0V6.25h-2a.75.75 0 0 0 0 1.5h2v1.5h1.5v-1.5h2a.75.75 0 0 0 0-1.5h-2zM5.25 10a.75.75 0 0 0 0 1.5h5.5a.75.75 0 0 0 0-1.5z" /></svg>;
}