// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconPin({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 1;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 16 16" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path fillRule="evenodd" d="M9.854.354a.5.5 0 0 1 .707 0l4.95 4.95a.5.5 0 0 1 0 .706l-.28.28a2.5 2.5 0 0 1-1.277.683l-.58.116a1.5 1.5 0 0 0-.767.41l-1.963 1.963c-.13.131-.197.35-.153.593.07.38.129.904.068 1.44-.06.535-.246 1.127-.705 1.587a.5.5 0 0 1-.708 0l-2.828-2.829-2.596 2.596c-.195.195-2.512 2.195-2.707 2-.196-.195 1.804-2.512 2-2.707L5.61 9.546 2.782 6.718a.5.5 0 0 1 0-.708c.46-.46 1.052-.645 1.587-.705a5 5 0 0 1 1.44.068c.242.044.462-.023.592-.153l1.964-1.963a1.5 1.5 0 0 0 .41-.767l.116-.58A2.5 2.5 0 0 1 9.575.632z" clipRule="evenodd" /></svg>;
}