// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconIndent({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 1;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 16 16" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path d="M13.25 2a.75.75 0 0 0-.75.75v10.5a.75.75 0 0 0 1.5 0V2.75a.75.75 0 0 0-.75-.75M6.47 4.22a.75.75 0 0 0 0 1.06l1.97 1.97H2.75a.75.75 0 0 0 0 1.5h5.69l-1.97 1.97a.75.75 0 1 0 1.06 1.06l3.25-3.25a.75.75 0 0 0 0-1.06L7.53 4.22a.75.75 0 0 0-1.06 0" /></svg>;
}