// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconHash({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 1;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 16 16" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path d="M11.77 1.575a.75.75 0 0 1 1.46.35L12.61 4.5h1.55a.75.75 0 0 1 0 1.5h-1.909l-.84 3.5h1.548a.75.75 0 0 1 0 1.5h-1.908l-.822 3.425a.75.75 0 0 1-1.46-.35L9.51 11H5.302l-.822 3.425a.75.75 0 0 1-1.46-.35L3.76 11H2.21a.75.75 0 0 1 0-1.5h1.908L4.96 6H3.41a.75.75 0 1 1 0-1.5h1.908l.703-2.925a.75.75 0 0 1 1.459.35L6.86 4.5h4.207zM5.662 9.5h4.207L10.71 6H6.502z" /></svg>;
}