// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconDiffRenamedFill({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 1;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 16 16" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path d="M8.176 5.297c.873 0 1.394.463 1.394 1.277 0 .82-.515 1.266-1.412 1.266h-1.43V5.297z" /><path fillRule="evenodd" d="M8 0c1.516 0 2.784.078 3.825.307 1.05.23 1.916.624 2.58 1.288s1.058 1.53 1.288 2.58C15.922 5.215 16 6.484 16 8s-.078 2.784-.307 3.825c-.23 1.05-.623 1.916-1.288 2.58-.664.665-1.53 1.058-2.58 1.288C10.785 15.922 9.516 16 8 16s-2.784-.078-3.825-.307c-1.05-.23-1.916-.623-2.58-1.288-.664-.664-1.058-1.53-1.288-2.58C.078 10.785 0 9.516 0 8s.078-2.784.307-3.825c.23-1.05.624-1.916 1.288-2.58S3.125.537 4.175.307C5.215.078 6.484 0 8 0M6.342 4.002c-.832 0-1.196.375-1.196 1.207v5.994c0 .54.293.856.797.856.498 0 .786-.317.786-.856v-2.18h1.453l1.177 2.32c.264.516.487.692.903.692.45 0 .785-.305.785-.732 0-.17-.053-.37-.14-.528l-1.16-2.127c.89-.375 1.411-1.183 1.411-2.197 0-1.512-1.06-2.449-2.771-2.449z" clipRule="evenodd" /></svg>;
}