// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconFilePlus({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 1;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 16 16" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path d="M9.5 1a.5.5 0 0 1 .354.146l4 4A.5.5 0 0 1 14 5.5v1.916A5 5 0 0 0 8 15H4.5A2.5 2.5 0 0 1 2 12.5v-9A2.5 2.5 0 0 1 4.5 1z" opacity={0.4} /><path fillRule="evenodd" d="M12 8a4 4 0 1 1 0 8 4 4 0 0 1 0-8m0 1.5a.5.5 0 0 0-.5.5v1.5H10a.5.5 0 0 0 0 1h1.5V14a.5.5 0 0 0 1 0v-1.5H14a.5.5 0 0 0 0-1h-1.5V10a.5.5 0 0 0-.5-.5" clipRule="evenodd" /></svg>;
}