// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconFileImage({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 1;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 16 16" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path d="M5.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3" /><path fillRule="evenodd" d="M10.75 0c.199 0 .39.08.53.22l3.5 3.5c.14.14.22.331.22.53v9A2.75 2.75 0 0 1 12.25 16h-8.5A2.75 2.75 0 0 1 1 13.25V2.75A2.75 2.75 0 0 1 3.75 0zm-7 1.5c-.69 0-1.25.56-1.25 1.25v8.097l1.608-.987a.75.75 0 0 1 .794.007L5 9.941l1.45 1.296 3-3.246a.75.75 0 0 1 1.055-.046l.055.057 2.94 3.307V5h-1.25A2.25 2.25 0 0 1 10 2.75V1.5z" clipRule="evenodd" /></svg>;
}