// Generated by `npm run icons:build`, do not edit manually.
import { Colors, type IconProps } from '../types';
export function IconTriangleFill({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * 1;
  return <svg xmlns="http://www.w3.org/2000/svg" fill={Colors[color] ?? color} viewBox="0 0 16 16" width={width} height={height} style={style} className={`pi${className != null ? ` ${className}` : ``}`} {...props} {...props}><path d="M7.997 0c2.788 0 8.866 11.839 7.9 13.645-.967 1.807-14.871 1.807-15.8 0S5.207 0 7.996 0" /><path d="M7.997 0c2.788 0 8.866 11.839 7.9 13.645-.967 1.807-14.871 1.807-15.8 0S5.207 0 7.996 0" /></svg>;
}