#!/usr/bin/env node
import { transform } from '@svgr/core';
import { mkdir, readFile, readdir, rm, stat, writeFile } from 'fs/promises';
import { basename, dirname, extname, join } from 'path';
import { fileURLToPath } from 'url';

import { SVGOConfig } from '../svgo.config.js';

import template from './svgr-template.js';

const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  dim: '\x1b[2m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
};

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');

/**
 * Clean up existing generated files
 */
async function cleanupGeneratedFiles(componentsDir: string) {
  console.log(
    `${colors.blue}► Cleaning up existing generated components...${colors.reset}`
  );

  try {
    const existingFiles = await readdir(componentsDir);
    const generatedFiles = existingFiles.filter(
      (file) => file.endsWith('.tsx') && file !== 'index.ts'
    );

    if (generatedFiles.length > 0) {
      for (const file of generatedFiles) {
        const filePath = join(componentsDir, file);
        await rm(filePath);
      }
      console.log(
        `${colors.dim}  🗑 Removed ${generatedFiles.length} existing components${colors.reset}`
      );
    } else {
      console.log(
        `${colors.dim}  ✓ No existing components to clean${colors.reset}`
      );
    }
  } catch {
    // Directory doesn't exist yet, will be created
  }
}

/**
 * Get component name from filename (just removes extension)
 */
function toComponentName(filename: string): string {
  return basename(filename, extname(filename));
}

/**
 * Process a single SVG file and generate React component
 */
async function processSvg(
  svgPath: string,
  outputDir: string
): Promise<{ name: string; filename: string }> {
  const svgContent = await readFile(svgPath, 'utf-8');
  const componentName = toComponentName(svgPath);
  const outputFilename = `${componentName}.tsx`;

  const componentCode = await transform(
    svgContent,
    {
      plugins: ['@svgr/plugin-svgo', '@svgr/plugin-jsx'],
      svgoConfig: SVGOConfig,
      template,
      typescript: true,
      jsxRuntime: 'automatic',
      svgProps: {
        xmlns: 'http://www.w3.org/2000/svg',
        fill: '{Colors[color] ?? color}',
        width: '{width}',
        height: '{height}',
        style: '{style}',
        className: '{`pi${className != null ? ` ${className}` : ``}`}',
        '{...props}': null,
      },
    },
    { componentName }
  );

  const outputPath = join(outputDir, outputFilename);
  await writeFile(outputPath, componentCode);

  return { name: componentName, filename: outputFilename };
}

/**
 * Generate index.ts that exports all icons
 */
async function generateIndex(
  icons: Array<{ name: string; filename: string }>,
  outputDir: string
) {
  const exports = icons
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(
      ({ name, filename }) =>
        `export { ${name} } from './${filename.replace('.tsx', '')}';`
    )
    .join('\n');

  const indexContent =
    icons.length > 0
      ? `// Generated by \`npm run icons:build\`, do not edit manually.
${exports}
`
      : `// Generated by \`npm run icons:build\`, do not edit manually.
// Add SVG files to the 'svg' directory and run \`npm run icons:build\` to generate icon components.
export {};
`;

  await writeFile(join(outputDir, 'index.ts'), indexContent);
}

/**
 * Main build function
 */
async function build() {
  console.log(
    `${colors.cyan}${colors.bright}Building icons...${colors.reset}\n`
  );

  const svgDir = join(projectRoot, 'svg');
  const outputDir = join(projectRoot, 'src', 'icons');

  // Ensure output directory exists
  await mkdir(outputDir, { recursive: true });

  // Clean up existing generated files
  await cleanupGeneratedFiles(outputDir);

  // Check if SVG directory exists
  try {
    await stat(svgDir);
  } catch {
    console.log(
      `${colors.dim}  ℹ No SVG directory found at ${svgDir}${colors.reset}`
    );
    console.log(
      `${colors.dim}  ℹ Create the 'svg' directory and add your SVG files to generate icons.${colors.reset}`
    );
    // Create empty index
    await generateIndex([], outputDir);
    return;
  }

  // Get all SVG files
  const files = await readdir(svgDir);
  const svgFiles = files.filter((file) => file.endsWith('.svg'));

  if (svgFiles.length === 0) {
    console.log(
      `${colors.dim}  ℹ No SVG files found in ${svgDir}${colors.reset}`
    );
    await generateIndex([], outputDir);
    return;
  }

  console.log(
    `${colors.blue}► Processing ${svgFiles.length} SVG files...${colors.reset}`
  );

  // Process all SVGs
  const icons: Array<{ name: string; filename: string }> = [];

  for (const svgFile of svgFiles) {
    try {
      const result = await processSvg(join(svgDir, svgFile), outputDir);
      icons.push(result);
      console.log(
        `${colors.dim}  ✓ ${svgFile} → ${result.name}${colors.reset}`
      );
    } catch (error) {
      console.error(
        `${colors.red}  ✗ Error processing ${svgFile}: ${error}${colors.reset}`
      );
    }
  }

  // Generate index file
  console.log(`\n${colors.blue}► Generating index file...${colors.reset}`);
  await generateIndex(icons, outputDir);

  console.log(
    `\n${colors.green}${colors.bright}✓ Generated ${icons.length} icon components${colors.reset}`
  );
}

build().catch((error) => {
  console.error(`${colors.red}Build failed: ${error}${colors.reset}`);
  process.exit(1);
});
