import * as babelTypes from '@babel/types';

interface TemplateVariables {
  componentName: string;
  jsx: babelTypes.JSXElement;
}

export default function template(
  variables: TemplateVariables,
  {
    tpl,
  }: { tpl: (strings: TemplateStringsArray, ...values: unknown[]) => unknown }
) {
  const { componentName, jsx } = variables;

  // Extract viewBox from JSX to calculate aspect ratio
  const viewBoxMatch = jsx.openingElement?.attributes?.find(
    (attr) =>
      babelTypes.isJSXAttribute(attr) &&
      babelTypes.isJSXIdentifier(attr.name) &&
      attr.name.name === 'viewBox'
  ) as babelTypes.JSXAttribute | undefined;

  let aspectRatio = 1;
  if (
    viewBoxMatch &&
    viewBoxMatch.value &&
    babelTypes.isStringLiteral(viewBoxMatch.value)
  ) {
    const viewBoxValues = viewBoxMatch.value.value.split(' ');
    if (viewBoxValues.length >= 4) {
      const [, , viewBoxWidth, viewBoxHeight] = viewBoxValues;
      aspectRatio = Number(viewBoxWidth) / Number(viewBoxHeight);
    }
  }

  const aspectRatioNode = babelTypes.numericLiteral(aspectRatio);

  return tpl`
// Generated by \`npm run icons:build\`, do not edit manually.
import { Colors, type IconProps } from '../types';

export function ${componentName}({
  size = 16,
  color = "currentcolor",
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === "1em" ? "1em" : Number(size) * ${aspectRatioNode};

  return (
    ${jsx}
  );
}
`;
}
